# Generated by Django 5.2.8 on 2025-11-22 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuncs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataclassas',
            name='datacheck',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dataclassas',
            name='hobbies',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
