# Generated by Django 5.2.8 on 2025-11-22 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuncs', '0002_dataclassas_datacheck_dataclassas_hobbies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataclassas',
            name='datacheck',
        ),
        migrations.CreateModel(
            name='clientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameData', models.CharField(max_length=200)),
                ('accountData', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cuncs.dataclassas')),
            ],
        ),
    ]
